# Generated by Django 4.0 on 2022-01-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadİmg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('imgcode', models.TextField()),
                ('username', models.CharField(max_length=80)),
                ('userid', models.CharField(max_length=5)),
                ('keyid', models.CharField(max_length=5)),
            ],
        ),
    ]
