# Generated by Django 4.0 on 2022-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadi̇mg',
            name='imgname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadi̇mg',
            name='keyid',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='uploadi̇mg',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadi̇mg',
            name='userid',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='uploadi̇mg',
            name='username',
            field=models.CharField(default='', max_length=80),
        ),
    ]
