# Generated by Django 4.0 on 2022-01-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_uploadi̇mg_imgname_alter_uploadi̇mg_keyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadi̇mg',
            name='imgname',
            field=models.ImageField(upload_to=''),
        ),
    ]
