# Generated by Django 4.0 on 2022-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_key_alter_user_mail_alter_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('key', models.CharField(max_length=120)),
            ],
        ),
    ]
