# Generated by Django 4.0 on 2022-01-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_keyuser_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyuser',
            name='key',
            field=models.CharField(max_length=256),
        ),
    ]
